create table if not exists public.gekokujo_scores (
  id bigint generated by default as identity primary key,
  name varchar(12) not null,
  score integer not null check (score between 0 and 99999999),
  combo integer not null check (combo between 0 and 999999),
  kills integer not null check (kills between 0 and 999999),
  play_time integer not null check (play_time between 0 and 86400),
  stage integer not null check (stage between 1 and 9999),
  character varchar(12) not null,
  created_at timestamptz not null default now(),
  constraint gekokujo_scores_name_length check (char_length(trim(name)) between 1 and 12)
);

create index if not exists gekokujo_scores_order_idx
  on public.gekokujo_scores (score desc, created_at asc);

alter table public.gekokujo_scores enable row level security;

revoke all on table public.gekokujo_scores from anon, authenticated;
grant select, insert on table public.gekokujo_scores to anon;

revoke all on sequence public.gekokujo_scores_id_seq from anon, authenticated;
grant usage, select on sequence public.gekokujo_scores_id_seq to anon;

drop policy if exists "Public scores are readable" on public.gekokujo_scores;
create policy "Public scores are readable"
  on public.gekokujo_scores
  for select
  to anon
  using (true);

drop policy if exists "Public scores are insertable" on public.gekokujo_scores;
create policy "Public scores are insertable"
  on public.gekokujo_scores
  for insert
  to anon
  with check (
    char_length(trim(name)) between 1 and 12
    and score between 0 and 99999999
    and combo between 0 and 999999
    and kills between 0 and 999999
    and play_time between 0 and 86400
    and stage between 1 and 9999
    and char_length(character) between 1 and 12
    and created_at between now() - interval '1 minute' and now() + interval '1 minute'
  );
